repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      # Git state
      - id: check-merge-conflict
        stages: [commit]
      - id: check-added-large-files
        stages: [commit]
      # Sensitive information
      - id: detect-private-key
        stages: [commit]
      - id: detect-aws-credentials
        stages: [commit]
      # Generic file state
      - id: trailing-whitespace
        stages: [commit]
      - id: mixed-line-ending
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      # Language syntax/formatting
      - id: check-yaml
        stages: [commit]
  - repo: https://github.com/mattlqx/pre-commit-ruby
    rev: v1.3.6
    hooks:
      - id: rubocop
        args: [--format, github]
        name: Check Ruby style with rubocop
        description: Enforce Ruby style guide with rubocop
        language: script
        types: ['ruby']
        stages: [commit]
        verbose: true
  - repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.1.1
    hooks:
      - id: sign-commit
